verification:
  path: /verification/webhook #call to any path that starts with /webhook, like /webhook/dmm or something will be catch
  token:
    in: query
    locate: hub.verify_token #this means that get the token from string query with param hub.verify_token
  challenge:
    in: query
    locate: hub.challenge #this means that get the token from string query with param hub.verify_toke
  response:
    type: text/plain # could be application/json
    data: "@challenge" #this means that get the challenge value, as plain text. Just handle @challenge case for now.
data:
  hello:
    path: /update/{id}
